[package]
name = "optcore"
version = "0.1.0"
authors = ["Tomas Tinoco De Rubira <ttinoco5687@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause"

[dependencies]
num-traits = "0.2.11"
sprs = "0.7.1"
