[package]
name = "optcore"
version = "0.1.0"
authors = ["Tomas Tinoco De Rubira <ttinoco5687@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
